const generatedPattern = /\b(?:ai[- ]generated|artificial intelligence|generated by|interpreted (?:by )?(?:gemini|midjourney|dall[- ]?e|stable diffusion)|facial reconstruction|reconstructed (?:face|portrait|image)|colori[sz]ed by ai)\b/i;
const excludedSubjectPattern = /\b(?:statue|sculpture|bust(?!\s+length)|monument|memorial|grave|tomb|signature|autograph|coat of arms|currency|banknote|coin|stamp)\b/i;
const groupPattern = /\b(?:group portrait|group photograph|group photo|family portrait|father and son|mother and daughter|father and daughter|mother and son|and (?:his|her|their )?(?:son|daughter|child|children)|with (?:his|her|their) (?:family|(?:four|three|two|\d+) (?:sons|daughters|children))|public rally|republican rally|political rally|conference on|holds? court|court scene|stand in attendance|darbar|durbar|de izquierda a derecha.{0,500}(?:de pie|sentados)|from left to right.{0,500}(?:standing|seated)|standing.{0,500}seated)\b/i;
const photoPattern = /\b(?:photographs?|photographic|photographer|photo portraits?|portrait photos?|daguerreotypes?|glass negatives?|collodion|albumen|carte[- ]de[- ]visite|cabinet cards?|photogravures?|foto|fotograf[ií]a)\b/i;
const paintingPattern = /\b(?:portrait paintings?|painting (?:by|of)|original painting|oil on canvas|oil paintings?|watercolou?rs?|pastel portraits?|miniature portraits?|painted portraits?|peinture|retrato|rafael uribe uribe \(1915\) by francisco antonio cano)\b|\b[oó]leo(?: sobre tela)?\b/i;
const printPattern = /\b(?:engravings?|engraved portrait|lithographs?|lithographie|lithografie|litograf[ií]a|woodcuts?|wood engraving|etching|mezzotint|printed portrait|print after|john chester buttre|metszet)\b/i;
const structuredTypeMap = new Map([
  ["Q125191", "photograph"],
  ["Q3305213", "painting"],
  ["Q11060274", "print"],
]);
const acceptedImageTypes = new Set(["photograph", "painting", "print"]);
const acceptedReviewDecisions = new Set(["approve", "reject"]);
const acceptedPersonReviewDecisions = new Set(["no_eligible_image", "identity_ambiguous"]);

export function combinedText(image) {
  return [
    image.title,
    image.description,
    image.mediaLabel,
    ...(image.categories || []),
  ].filter(Boolean).join(" ");
}

export function exclusionReason(image) {
  const text = combinedText(image);
  if (generatedPattern.test(text)) return "generated or reconstructed image";
  if (excludedSubjectPattern.test(text)) return "not a two-dimensional portrait of the person";
  if (groupPattern.test(text)) return "group image";
  return "";
}

export function classifyImageType(image) {
  const text = combinedText(image);
  if (paintingPattern.test(text)) return "painting";
  if (printPattern.test(text)) return "print";
  for (const qid of image.structuredTypes || []) {
    if (structuredTypeMap.has(qid)) return structuredTypeMap.get(qid);
  }
  if (photoPattern.test(text)) return "photograph";
  return "";
}

export function identityEvidence(image, person) {
  if ((image.depicts || []).includes(person.wikidataId)) return "structured depicts statement";
  if (image.directPersonImage) return "Wikidata image statement for exact person";
  const normalizedName = normalize(person.name);
  if (!normalizedName) return "";
  const portraitCategory = (image.categories || []).find((category) => {
    const normalizedCategory = normalize(category.replace(/^Category:/i, ""));
    return normalizedCategory.includes(normalizedName)
      && /portrait|photograph|painting|print|engraving|lithograph|daguerreotype/.test(normalizedCategory);
  });
  if (portraitCategory) return "portrait category names person";
  const description = normalize(`${image.mediaLabel || ""} ${image.description || ""}`);
  if (description.includes(normalizedName) && /portrait|photograph|daguerreotype|painting|engraving|lithograph/.test(description)) {
    return "file description names person";
  }
  return "";
}

export function selectImage(images, person) {
  const ranked = images.map((image) => {
    const excluded = exclusionReason(image);
    const type = classifyImageType(image);
    const evidence = identityEvidence(image, person);
    if (excluded || !type || !evidence || !image.license) return null;
    const typeScore = { photograph: 30, painting: 20, print: 10 }[type] || 0;
    const evidenceScore = {
      "structured depicts statement": 300,
      "portrait category names person": 200,
      "file description names person": 100,
    }[evidence] || 0;
    const preferredScore = image.wikidataRank === "preferred" ? 20 : 0;
    return { image, score: evidenceScore + typeScore + preferredScore };
  }).filter(Boolean).sort((left, right) => right.score - left.score || left.image.title.localeCompare(right.image.title));
  return ranked[0]?.image || null;
}

export function validateImageReviewDocument(document) {
  if (document?.schema_version !== 2) throw new Error("Historical character image reviews must use schema_version 2");
  if (!Array.isArray(document.reviews)) throw new Error("Historical character image reviews must contain a reviews array");
  if (!Array.isArray(document.person_reviews)) throw new Error("Historical character image reviews must contain a person_reviews array");
  const seen = new Set();
  const approvedPeople = new Set();
  const imageReviews = document.reviews.map((source, index) => {
    const label = `image review ${index + 1}`;
    const characterKeys = [...new Set((source.character_keys || []).map((value) => String(value).trim()).filter(Boolean))].sort();
    if (!characterKeys.length) throw new Error(`${label} must include character_keys`);
    if (!/^Q\d+$/.test(String(source.wikidata_id || ""))) throw new Error(`${label} must include a Wikidata QID`);
    if (!/^File:/.test(String(source.file_title || ""))) throw new Error(`${label} must include a Commons file title`);
    if (!acceptedReviewDecisions.has(source.decision)) throw new Error(`${label} has an invalid decision`);
    if (source.decision === "approve" && !acceptedImageTypes.has(source.type)) throw new Error(`${label} has an invalid approved image type`);
    if (source.decision === "reject" && source.type) throw new Error(`${label} must not assign a type to a rejected image`);
    if (!/^\d{4}-\d{2}-\d{2}$/.test(String(source.reviewed_at || "")) || Number.isNaN(Date.parse(`${source.reviewed_at}T00:00:00Z`))) {
      throw new Error(`${label} must include a valid review date`);
    }
    if (!String(source.reason || "").trim()) throw new Error(`${label} must include a reason`);
    const review = {
      character_keys: characterKeys,
      wikidata_id: String(source.wikidata_id),
      file_title: String(source.file_title),
      decision: source.decision,
      type: source.decision === "approve" ? source.type : "",
      reviewed_at: String(source.reviewed_at),
      reason: String(source.reason).trim(),
    };
    const key = imageReviewKey(review);
    if (seen.has(key)) throw new Error(`${label} duplicates an existing person and file decision`);
    seen.add(key);
    const personKey = imageReviewPersonKey(review);
    if (review.decision === "approve" && approvedPeople.has(personKey)) throw new Error(`${label} duplicates an approved person decision`);
    if (review.decision === "approve") approvedPeople.add(personKey);
    return review;
  });
  const seenPeople = new Set();
  const personReviews = document.person_reviews.map((source, index) => {
    const label = `person review ${index + 1}`;
    const characterKeys = validatedSortedUniqueStrings(source.character_keys, `${label} character_keys`);
    const wikidataIds = validatedSortedUniqueStrings(source.wikidata_ids, `${label} wikidata_ids`);
    const candidateFileTitles = validatedSortedUniqueStrings(source.candidate_file_titles, `${label} candidate_file_titles`, true);
    if (!wikidataIds.every((value) => /^Q\d+$/.test(value))) throw new Error(`${label} wikidata_ids must contain Wikidata QIDs`);
    if (!candidateFileTitles.every((value) => /^File:/.test(value))) throw new Error(`${label} candidate_file_titles must contain Commons file titles`);
    if (!acceptedPersonReviewDecisions.has(source.decision)) throw new Error(`${label} has an invalid decision`);
    if (source.decision === "identity_ambiguous" && wikidataIds.length < 2) throw new Error(`${label} identity_ambiguous requires multiple Wikidata people`);
    if (!/^\d{4}-\d{2}-\d{2}$/.test(String(source.reviewed_at || "")) || Number.isNaN(Date.parse(`${source.reviewed_at}T00:00:00Z`))) {
      throw new Error(`${label} must include a valid review date`);
    }
    if (!String(source.reason || "").trim()) throw new Error(`${label} must include a reason`);
    const review = {
      character_keys: characterKeys,
      wikidata_ids: wikidataIds,
      candidate_file_titles: candidateFileTitles,
      decision: source.decision,
      reviewed_at: String(source.reviewed_at),
      reason: String(source.reason).trim(),
    };
    const key = personReviewKey(review);
    if (seenPeople.has(key)) throw new Error(`${label} duplicates an existing person terminal decision`);
    seenPeople.add(key);
    const conflictKey = `${characterKeys.join("\u0001")}\u0000${wikidataIds.length === 1 ? wikidataIds[0] : ""}`;
    if (wikidataIds.length === 1 && approvedPeople.has(conflictKey)) throw new Error(`${label} conflicts with an approved image review`);
    return review;
  });
  return { image_reviews: imageReviews, person_reviews: personReviews };
}

export function personReviewKey(review) {
  return `${(review.character_keys || []).join("\u0001")}\u0000${(review.wikidata_ids || []).join("\u0001")}`;
}

export function personReviewForCandidateState(personReviews, person) {
  const characterKeys = [...new Set((person.character_keys || []).map(String))].sort();
  const applicable = (personReviews || []).filter((review) => sameStringArray(review.character_keys, characterKeys));
  if (!applicable.length) return null;
  if (applicable.length > 1) throw new Error(`Multiple terminal person reviews for ${person.name_en || characterKeys.join(", ")}`);
  const review = applicable[0];
  const wikidataIds = [...new Set((person.wikidata_ids || []).map(String))].sort();
  const candidateFileTitles = [...new Set((person.candidate_file_titles || []).map(String))].sort();
  if (!sameStringArray(review.wikidata_ids, wikidataIds) || !sameStringArray(review.candidate_file_titles, candidateFileTitles)) {
    throw new Error(`Reviewed person candidate state changed for ${person.name_en || characterKeys.join(", ")}`);
  }
  return review;
}

export function imageReviewsForPerson(reviews, person) {
  const characterKeys = [...new Set((person.character_keys || []).map(String))].sort();
  const wikidataId = String(person.wikidataId || person.wikidata_id || "");
  return (reviews || []).filter((review) => (
    review.wikidata_id === wikidataId
    && sameStringArray(review.character_keys, characterKeys)
  ));
}

export function imageReviewKey(review) {
  return `${imageReviewPersonKey(review)}\u0000${review.file_title}`;
}

export function filterRejectedImages(images, person, reviews) {
  const rejected = new Set(imageReviewsForPerson(reviews, person)
    .filter((review) => review.decision === "reject")
    .map((review) => review.file_title));
  return (images || []).filter((image) => !rejected.has(image.title));
}

export function selectReviewedImage(images, person, reviews) {
  const applicable = imageReviewsForPerson(reviews, person);
  for (const review of applicable) {
    if (!(images || []).some((image) => image.title === review.file_title)) {
      throw new Error(`Reviewed Commons file is absent for ${person.name_en || person.name || review.wikidata_id}: ${review.file_title}`);
    }
  }
  const approved = applicable.filter((review) => review.decision === "approve");
  if (!approved.length) return null;
  if (approved.length > 1) throw new Error(`Multiple approved images for ${person.name_en || person.name || approved[0].wikidata_id}`);
  const review = approved[0];
  const candidate = images.find((image) => image.title === review.file_title);
  const excluded = exclusionReason(candidate);
  if (excluded) throw new Error(`Reviewed image violates exclusion rules: ${excluded}`);
  const evidence = identityEvidence(candidate, person);
  if (!evidence) throw new Error("Reviewed image lacks person-specific identity evidence");
  if (!candidate.license) throw new Error("Reviewed image lacks license information");
  return {
    image: { ...candidate, type: review.type },
    review,
    identity_evidence: evidence,
  };
}

export function normalize(value) {
  return String(value || "")
    .normalize("NFKD")
    .replace(/[\u0300-\u036f]/g, "")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, " ")
    .trim();
}

function imageReviewPersonKey(review) {
  return `${[...(review.character_keys || [])].sort().join("\u0001")}\u0000${review.wikidata_id}`;
}

function sameStringArray(left, right) {
  return left.length === right.length && left.every((value, index) => value === right[index]);
}

function validatedSortedUniqueStrings(values, label, allowEmpty = false) {
  if (!Array.isArray(values)) throw new Error(`${label} must be an array`);
  const strings = values.map((value) => String(value).trim());
  if ((!allowEmpty && !strings.length) || strings.some((value) => !value)) throw new Error(`${label} must not be empty`);
  const sorted = [...new Set(strings)].sort();
  if (!sameStringArray(strings, sorted)) throw new Error(`${label} must be sorted and unique`);
  return strings;
}

export function mediaInfoRows(data) {
  return Object.values(data.entities || {}).map((entity) => ({
    page_id: Number(String(entity.id || "").replace(/^M/, "")),
    depicts: claimEntityIds(entity.statements?.P180 || entity.claims?.P180),
    structured_types: claimEntityIds(entity.statements?.P31 || entity.claims?.P31),
  })).filter((row) => row.page_id);
}

export function nameVariants(person) {
  const variants = [];
  for (const key of person.character_keys || []) {
    const keyName = key
      .replace(/^(?:[a-z]{3}|agitator|ruler|commander|general|admiral|historical)_/i, "")
      .replace(/_(?:character_)?template$/i, "")
      .replace(/_(?:character|historical|ruler|general|admiral)$/i, "")
      .split("_")
      .filter(Boolean)
      .map(titleToken)
      .join(" ");
    addVariant(variants, keyName, person.name_en);
  }
  const asciiName = String(person.name_en || "").normalize("NFKD").replace(/[\u0300-\u036f]/g, "");
  addVariant(variants, asciiName, person.name_en);
  const tokens = String(person.name_en || "").split(/\s+/).filter(Boolean);
  if (tokens.length > 1) {
    const withoutDynasty = tokens.filter((token) => !/^(?:osmanoglu|romanov|yamato|braganca|bragança)$/i.test(token)).join(" ");
    addVariant(variants, withoutDynasty, person.name_en);
    addVariant(variants, withoutDynasty.normalize("NFKD").replace(/[\u0300-\u036f]/g, ""), person.name_en);
    addVariant(variants, tokens.filter((token) => !/^(?:of|de|da|do|dos|del|della|di|von|van|al|el)$/i.test(token)).join(" "), person.name_en);
    addVariant(variants, tokens[0], person.name_en);
  }
  return variants.slice(0, 4);
}

export async function queryBatchWithSplit(batch, query, options = {}) {
  const delayMs = options.delayMs || 0;
  try {
    return await query(batch);
  } catch (error) {
    if (batch.length <= 1) {
      return [{ query_error: String(error?.message || error), input: batch[0] }];
    }
    const middle = Math.ceil(batch.length / 2);
    await delay(delayMs);
    const left = await queryBatchWithSplit(batch.slice(0, middle), query, options);
    await delay(delayMs);
    const right = await queryBatchWithSplit(batch.slice(middle), query, options);
    return [...left, ...right];
  }
}

export function derivedNameCandidate(person) {
  if (!Array.isArray(person.wikidata_candidates) || person.wikidata_candidates.length !== 1) return null;
  const candidate = person.wikidata_candidates[0];
  const hasMultiTokenMatch = (candidate.matched_variants || []).some((value) => normalize(value).split(/\s+/).filter(Boolean).length >= 2);
  return hasMultiTokenMatch ? candidate : null;
}

export function eligibleUndatedCandidates(person, candidates) {
  const dated = (candidates || []).filter((candidate) => /^\d{4}-/.test(String(candidate.birth || "")));
  if (!(person.expected_birth_years || []).length) return [];
  const expected = new Set(person.expected_birth_years.map(Number));
  return dated.filter((candidate) => expected.has(Number(String(candidate.birth).slice(0, 4))));
}

function addVariant(list, value, original) {
  const cleaned = String(value || "").replace(/\s+/g, " ").trim();
  const folded = cleaned.toLowerCase();
  if (!cleaned || folded === String(original || "").trim().toLowerCase() || list.some((item) => item.toLowerCase() === folded)) return;
  list.push(cleaned);
}

function titleToken(value) {
  if (/^[ivxlcdm]+$/i.test(value)) return value.toUpperCase();
  if (/^(?:de|da|do|dos|del|della|di|von|van|al|el)$/i.test(value)) return value.toLowerCase();
  return value.charAt(0).toUpperCase() + value.slice(1);
}

function claimEntityIds(claims) {
  return (claims || []).map((claim) => claim.mainsnak?.datavalue?.value?.id).filter(Boolean);
}

export async function fetchWithRetry(url, options = {}) {
  const {
    attempts = 5,
    delayMs = 6000,
    fetchImpl = fetch,
    userAgent = "VicdataPortraitResearch/0.1 (historical character image audit)",
    ...fetchOptions
  } = options;
  for (let attempt = 1; attempt <= attempts; attempt += 1) {
    try {
      const response = await fetchImpl(url, {
        ...fetchOptions,
        headers: { "User-Agent": userAgent, ...(fetchOptions.headers || {}) },
      });
      if (response.ok) return response;
      if (![429, 500, 502, 503, 504].includes(response.status) || attempt === attempts) {
        throw new Error(`${response.status} ${response.statusText}`);
      }
      const retryAfter = Number(response.headers.get("retry-after"));
      await delay(Number.isFinite(retryAfter) && retryAfter > 0 ? retryAfter * 1000 : delayMs * attempt);
    } catch (error) {
      if (attempt === attempts || error?.name === "AbortError") throw error;
      await delay(delayMs * attempt);
    }
  }
  throw new Error("unreachable");
}

function delay(milliseconds) {
  return milliseconds > 0 ? new Promise((resolve) => setTimeout(resolve, milliseconds)) : Promise.resolve();
}
