const generatedPattern = /\b(?:ai[- ]generated|artificial intelligence|generated by|interpreted (?:by )?(?:gemini|midjourney|dall[- ]?e|stable diffusion)|facial reconstruction|reconstructed (?:face|portrait|image)|colori[sz]ed by ai)\b/i;
const excludedSubjectPattern = /\b(?:statue|sculpture|bust|monument|memorial|grave|tomb|signature|autograph|coat of arms|currency|banknote|coin|stamp)\b/i;
const groupPattern = /\b(?:group portrait|group photograph|family portrait|father and son|mother and daughter|father and daughter|mother and son|with (?:his|her|their) (?:family|(?:four|three|two|\d+) (?:sons|daughters|children))|public rally|republican rally|political rally|conference on|holds? court|court scene|stand in attendance|darbar|durbar|de izquierda a derecha.{0,500}(?:de pie|sentados)|from left to right.{0,500}(?:standing|seated)|standing.{0,500}seated)\b/i;
const photoPattern = /\b(?:photographs?|photographic|photographer|photo portraits?|portrait photos?|daguerreotypes?|glass negatives?|collodion|albumen|carte[- ]de[- ]visite|cabinet cards?|photogravures?|foto|fotograf[ií]a)\b/i;
const paintingPattern = /\b(?:portrait paintings?|painting (?:by|of)|original painting|oil on canvas|oil paintings?|watercolou?rs?|pastel portraits?|miniature portraits?|painted portraits?|peinture|retrato|rafael uribe uribe \(1915\) by francisco antonio cano)\b|\b[oó]leo(?: sobre tela)?\b/i;
const printPattern = /\b(?:engravings?|engraved portrait|lithographs?|lithographie|lithografie|litograf[ií]a|woodcuts?|wood engraving|etching|mezzotint|printed portrait|print after|john chester buttre|metszet)\b/i;
const structuredTypeMap = new Map([
  ["Q125191", "photograph"],
  ["Q3305213", "painting"],
  ["Q11060274", "print"],
]);

export function combinedText(image) {
  return [
    image.title,
    image.description,
    image.mediaLabel,
    ...(image.categories || []),
  ].filter(Boolean).join(" ");
}

export function exclusionReason(image) {
  const text = combinedText(image);
  if (generatedPattern.test(text)) return "generated or reconstructed image";
  if (excludedSubjectPattern.test(text)) return "not a two-dimensional portrait of the person";
  if (groupPattern.test(text)) return "group image";
  return "";
}

export function classifyImageType(image) {
  const text = combinedText(image);
  if (paintingPattern.test(text)) return "painting";
  if (printPattern.test(text)) return "print";
  for (const qid of image.structuredTypes || []) {
    if (structuredTypeMap.has(qid)) return structuredTypeMap.get(qid);
  }
  if (photoPattern.test(text)) return "photograph";
  return "";
}

export function identityEvidence(image, person) {
  if ((image.depicts || []).includes(person.wikidataId)) return "structured depicts statement";
  if (image.directPersonImage) return "Wikidata image statement for exact person";
  const normalizedName = normalize(person.name);
  if (!normalizedName) return "";
  const portraitCategory = (image.categories || []).find((category) => {
    const normalizedCategory = normalize(category.replace(/^Category:/i, ""));
    return normalizedCategory.includes(normalizedName)
      && /portrait|photograph|painting|print|engraving|lithograph|daguerreotype/.test(normalizedCategory);
  });
  if (portraitCategory) return "portrait category names person";
  const description = normalize(`${image.mediaLabel || ""} ${image.description || ""}`);
  if (description.includes(normalizedName) && /portrait|photograph|daguerreotype|painting|engraving|lithograph/.test(description)) {
    return "file description names person";
  }
  return "";
}

export function selectImage(images, person) {
  const ranked = images.map((image) => {
    const excluded = exclusionReason(image);
    const type = classifyImageType(image);
    const evidence = identityEvidence(image, person);
    if (excluded || !type || !evidence || !image.license) return null;
    const typeScore = { photograph: 30, painting: 20, print: 10 }[type] || 0;
    const evidenceScore = {
      "structured depicts statement": 300,
      "portrait category names person": 200,
      "file description names person": 100,
    }[evidence] || 0;
    const preferredScore = image.wikidataRank === "preferred" ? 20 : 0;
    return { image, score: evidenceScore + typeScore + preferredScore };
  }).filter(Boolean).sort((left, right) => right.score - left.score || left.image.title.localeCompare(right.image.title));
  return ranked[0]?.image || null;
}

export function normalize(value) {
  return String(value || "")
    .normalize("NFKD")
    .replace(/[\u0300-\u036f]/g, "")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, " ")
    .trim();
}

export function mediaInfoRows(data) {
  return Object.values(data.entities || {}).map((entity) => ({
    page_id: Number(String(entity.id || "").replace(/^M/, "")),
    depicts: claimEntityIds(entity.statements?.P180 || entity.claims?.P180),
    structured_types: claimEntityIds(entity.statements?.P31 || entity.claims?.P31),
  })).filter((row) => row.page_id);
}

export function nameVariants(person) {
  const variants = [];
  for (const key of person.character_keys || []) {
    const keyName = key
      .replace(/^(?:[a-z]{3}|agitator|ruler|commander|general|admiral|historical)_/i, "")
      .replace(/_(?:character_)?template$/i, "")
      .replace(/_(?:character|historical|ruler|general|admiral)$/i, "")
      .split("_")
      .filter(Boolean)
      .map(titleToken)
      .join(" ");
    addVariant(variants, keyName, person.name_en);
  }
  const asciiName = String(person.name_en || "").normalize("NFKD").replace(/[\u0300-\u036f]/g, "");
  addVariant(variants, asciiName, person.name_en);
  const tokens = String(person.name_en || "").split(/\s+/).filter(Boolean);
  if (tokens.length > 1) {
    const withoutDynasty = tokens.filter((token) => !/^(?:osmanoglu|romanov|yamato|braganca|bragança)$/i.test(token)).join(" ");
    addVariant(variants, withoutDynasty, person.name_en);
    addVariant(variants, withoutDynasty.normalize("NFKD").replace(/[\u0300-\u036f]/g, ""), person.name_en);
    addVariant(variants, tokens.filter((token) => !/^(?:of|de|da|do|dos|del|della|di|von|van|al|el)$/i.test(token)).join(" "), person.name_en);
    addVariant(variants, tokens[0], person.name_en);
  }
  return variants.slice(0, 4);
}

export async function queryBatchWithSplit(batch, query, options = {}) {
  const delayMs = options.delayMs || 0;
  try {
    return await query(batch);
  } catch (error) {
    if (batch.length <= 1) {
      return [{ query_error: String(error?.message || error), input: batch[0] }];
    }
    const middle = Math.ceil(batch.length / 2);
    await delay(delayMs);
    const left = await queryBatchWithSplit(batch.slice(0, middle), query, options);
    await delay(delayMs);
    const right = await queryBatchWithSplit(batch.slice(middle), query, options);
    return [...left, ...right];
  }
}

export function derivedNameCandidate(person) {
  if (!Array.isArray(person.wikidata_candidates) || person.wikidata_candidates.length !== 1) return null;
  const candidate = person.wikidata_candidates[0];
  const hasMultiTokenMatch = (candidate.matched_variants || []).some((value) => normalize(value).split(/\s+/).filter(Boolean).length >= 2);
  return hasMultiTokenMatch ? candidate : null;
}

export function eligibleUndatedCandidates(person, candidates) {
  const dated = (candidates || []).filter((candidate) => /^\d{4}-/.test(String(candidate.birth || "")));
  if (!(person.expected_birth_years || []).length) return [];
  const expected = new Set(person.expected_birth_years.map(Number));
  return dated.filter((candidate) => expected.has(Number(String(candidate.birth).slice(0, 4))));
}

function addVariant(list, value, original) {
  const cleaned = String(value || "").replace(/\s+/g, " ").trim();
  const folded = cleaned.toLowerCase();
  if (!cleaned || folded === String(original || "").trim().toLowerCase() || list.some((item) => item.toLowerCase() === folded)) return;
  list.push(cleaned);
}

function titleToken(value) {
  if (/^[ivxlcdm]+$/i.test(value)) return value.toUpperCase();
  if (/^(?:de|da|do|dos|del|della|di|von|van|al|el)$/i.test(value)) return value.toLowerCase();
  return value.charAt(0).toUpperCase() + value.slice(1);
}

function claimEntityIds(claims) {
  return (claims || []).map((claim) => claim.mainsnak?.datavalue?.value?.id).filter(Boolean);
}

export async function fetchWithRetry(url, options = {}) {
  const {
    attempts = 5,
    delayMs = 6000,
    fetchImpl = fetch,
    userAgent = "VicdataPortraitResearch/0.1 (historical character image audit)",
    ...fetchOptions
  } = options;
  for (let attempt = 1; attempt <= attempts; attempt += 1) {
    try {
      const response = await fetchImpl(url, {
        ...fetchOptions,
        headers: { "User-Agent": userAgent, ...(fetchOptions.headers || {}) },
      });
      if (response.ok) return response;
      if (![429, 500, 502, 503, 504].includes(response.status) || attempt === attempts) {
        throw new Error(`${response.status} ${response.statusText}`);
      }
      const retryAfter = Number(response.headers.get("retry-after"));
      await delay(Number.isFinite(retryAfter) && retryAfter > 0 ? retryAfter * 1000 : delayMs * attempt);
    } catch (error) {
      if (attempt === attempts || error?.name === "AbortError") throw error;
      await delay(delayMs * attempt);
    }
  }
  throw new Error("unreachable");
}

function delay(milliseconds) {
  return milliseconds > 0 ? new Promise((resolve) => setTimeout(resolve, milliseconds)) : Promise.resolve();
}
