import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import { readSiteAppSource, readSiteStyleSource } from "./site_frontend_sources.mjs";

const root = process.cwd();
const app = readSiteAppSource(root);
const index = fs.readFileSync(path.join(root, "site", "index.html"), "utf8");
const styles = readSiteStyleSource(root);
const technologyChunk = readGlobal(path.join(root, "site", "versions", "1.13.9", "data-technologies.js"));
const technologyRenderer = app.match(/function renderTechnologyBoard\(\) \{[\s\S]*?\n}\n\nfunction renderTechnologyDetail/)[0];

assert.match(app, /function renderTechnologyBoard\(/, "technology board renderer must exist");
assert.match(app, /function renderTechnologyDetail\(/, "technology detail renderer must exist");
assert.match(app, /id: `technology:\$\{technology\.key\}`/, "global search must include technology entries");
assert.match(app, /kind === "technology"\) replaceHash\(`\/technology\/\$\{encodeURIComponent\(key\)\}`\)/, "global search must navigate technology entries to their detail route");
assert.match(app, /technologyGraphLayout/, "technology graph layout must exist");
assert.match(app, /const technologyGraphCategory = state\.technologyCategory/, "technology graph must render the selected category only");
assert.match(app, /const eraBaseRows = \[0, 2, 4, 6, 8\]/, "technology graph must reserve two grid rows for each era");
assert.match(app, /eraBaseRows\[eraIndex\]/, "technology graph must place era I at the top and era V at the bottom");
assert.match(app, /technologyGraphCategory/, "technology graph must keep category trees independent");
assert.match(app, /const technologyGridColumns = Math\.max\(1, \.\.\.Object\.values\(technologyPositions\)\.map\(\(position\) => position\.column\)\)/, "technology graph must size its canvas to the current category's rightmost technology");
assert.match(app, /const technologyGridRows = Math\.max\(1, \.\.\.Object\.values\(technologyPositions\)\.map\(\(position\) => position\.row\)\)/, "technology graph must size its canvas to the current category's lowest technology");
assert.match(app, /technologyGridPositions/, "technology graph must support explicitly placed technologies");
assert.match(app, /function technologyGraphEdges/, "technology graph must generate relationship edges between placed technologies");
assert.match(app, /data-technology-key/, "technology nodes must expose stable keys");
assert.match(app, /data-technology-target/, "technology detail links must expose targets");
assert.match(app, /assets\/technologies\//, "technology nodes must use published technology icons");
assert.doesNotMatch(app, /technology-node-category/, "technology node cards must not repeat their category label");
assert.match(styles, /technology-graph-viewport/, "desktop graph viewport styles must exist");
assert.match(styles, /\.technology-grid-overlay \{ display: none; \}/, "technology board must hide all placement grid lines");
assert.match(styles, /\.technology-graph-edges/, "technology graph must style relationship edges");
assert.match(styles, /\.technology-graph-edges path\.is-highlighted/, "technology graph must highlight selected technology relationships");
assert.match(styles, /technology-local-graph/, "narrow-screen local graph styles must exist");
assert.match(styles, /\.technology-node \{[^}]*flex-direction: column/s, "technology node cards must stack icon above name");
assert.match(styles, /\.technology-node \{[^}]*text-align: center/s, "technology node card names must be centered");
assert.match(styles, /\.technology-node \{[^}]*width: 144px/s, "technology node cards must keep the original readable width");
assert.match(app, /const technologyGridCellWidth = 83/, "technology grid column width must be sixty percent of its current size");
assert.match(app, /const technologyGridCellHeight = 138/, "technology grid row height must return to 138px");
assert.match(app, /technologySearch: ""/, "technology board must retain its local technology search state");
assert.match(technologyRenderer, /data-technology-category-select/, "technology board must use a category select control");
assert.match(technologyRenderer, /data-technology-search/, "technology board must expose a local search input");
assert.doesNotMatch(technologyRenderer, /technology-era-headings/, "technology board must not render era labels beside the canvas");
assert.match(technologyRenderer, /els\.resultCount\.textContent = ""/, "technology view must not show a generic technology count");
assert.match(styles, /body\[data-view="technology"\] \.results > \.panel-head,[\s\S]*?\.result-head \{ display: none; \}/, "technology view must hide the generic list header and sort control");
assert.match(styles, /body\[data-view="technology"\]:not\(\.detail-page\) \.results \{[^}]*right: 0/s, "technology canvas must span the page when no technology is selected");
assert.match(styles, /body\[data-view="technology"\] \.results \{[^}]*inset: 0/s, "technology surface must occupy the entire area below the top bar");
assert.match(styles, /body\[data-view="technology"\]:not\(\.detail-page\) \.detail \{[\s\S]*?display: none/, "technology detail must not reduce the canvas before a node is selected");
assert.match(styles, /body\.detail-page\[data-view="technology"\] \.results \{[\s\S]*?right: 20vw/s, "technology detail page must reserve the right twenty percent for details");
assert.match(styles, /body\.detail-page\[data-view="technology"\] \.detail \{[\s\S]*?width: 20vw/s, "technology detail panel must occupy twenty percent of the page width");
assert.match(app, /data-technology-back/, "selected technology detail must expose a return button");
assert.match(index, /data-nav-view="technology"[^>]*>[\s\S]*?<span>科技<\/span>/, "top navigation must provide a technology entry");
assert.match(index, /data-nav-view="technology"[^>]*>[\s\S]*?lightbulb\.svg/, "technology navigation must use the lightbulb icon");
assert.match(technologyRenderer, /data-technology-reset[^>]*aria-label="重置视图"[^>]*>[\s\S]*?refresh-ccw\.svg/, "technology reset control must use the shared reset icon");
assert.match(app, /location\.hash = "\/technology"/, "technology detail return button must clear the selected technology route");
assert.match(app, /if \(!technology\) return ""/, "technology detail renderer must render no right-panel content when no technology is selected");
assert.match(technologyRenderer, /button\.addEventListener\("pointerdown", \(event\) => event\.stopPropagation\(\)\)/, "technology card presses must not begin canvas dragging");
assert.match(technologyRenderer, /if \(event\.target\.closest\("\.technology-node"\)\) return/, "canvas dragging must ignore technology cards");
assert.match(app, /state\.selectedTechnology = "";\s*state\.detailKind = "technology";/, "opening the unselected technology route must clear the previous selected technology");
assert.match(app, /function technologyEdgePath\(from, to\)/, "technology relationships must calculate paths from both endpoint positions");
assert.doesNotMatch(app, /const vertical = Math\.abs\(toCenterY - fromCenterY\)/, "technology relationships must not use left or right card ports");
assert.match(app, /const startY = downward \? from\.y \+ cardHeight : from\.y/, "technology relationships must leave only the top or bottom card edge");
assert.match(app, /const endY = downward \? to\.y : to\.y \+ cardHeight/, "technology relationships must enter only the top or bottom card edge");
assert.match(app, /const stubLength = 16/, "technology relationships must leave each vertical card port by a 16px segment");
assert.match(app, /Q\$\{startCurveX\} \$\{startStubY\} \$\{startDiagonalX\} \$\{startDiagonalY\}/, "technology relationships must round the source transition into the diagonal segment");
assert.match(app, /Q\$\{endCurveX\} \$\{endStubY\} \$\{toCenterX\} \$\{endCurveY\} V\$\{endY\}/, "technology relationships must round the target transition into the vertical port");
assert.match(app, /const endCurveY = endStubY \+ \(downward \? curveLength : -curveLength\)/, "technology relationship target curves must turn toward the card rather than away from it");
assert.match(technologyRenderer, /fill:none !important/, "technology relationship paths must explicitly disable fill to prevent opaque SVG shapes");
assert.match(app, /const technologyGridPositions = \{[\s\S]*?nitrogen_fixation: \{ column: 1, row: 8 \}/, "production technology positions must define nitrogen fixation at row eight column one");
assert.match(app, /automatic_bottle_blowers: \{ column: 25, row: 8 \}/, "production technology positions must define automatic bottle blowers at row eight column twenty-five");
assert.match(app, /arc_welding: \{ column: 7, row: 10 \}/, "production technology positions must define arc welding at row ten column seven");
assert.match(app, /rubber_mastication: \{ column: 23, row: 6 \}/, "production technology positions must define rubber mastication at row six column twenty-three");
assert.match(app, /nitroglycerin: \{ column: 10, row: 5 \}/, "production technology positions must define nitroglycerin at row five column ten");
assert.match(app, /canneries: \{ column: 26, row: 4 \}/, "production technology positions must define canneries at row four column twenty-six");
assert.match(app, /enclosure: \{ column: 14, row: 1 \}/, "production technology positions must define enclosure at row one column fourteen");
assert.match(app, /sericulture: \{ column: 10, row: 1 \}/, "production technology positions must define sericulture at row one column ten");
assert.match(app, /shaft_mining: \{ column: 17, row: 2 \}/, "production technology positions must define shaft mining at row two column seventeen");
assert.match(technologyRenderer, /style="fill:none !important;stroke:\$\{[^}]+\} !important;stroke-width:\$\{[^}]+\} !important"/, "technology edges must write explicit SVG fill and stroke styles");
assert.match(app, /military: \{[\s\S]*?standing_army: \{ column: 7, row: 1 \}/, "military technology positions must define standing army at row one column seven");
assert.match(app, /enlistment_offices: \{ column: 3, row: 7 \}/, "military technology positions must define enlistment offices at row seven column three");
assert.match(app, /electric_telegraph: \{ column: 9, row: 7 \}/, "military technology positions must define electric telegraph at row seven column nine");
assert.match(app, /war_propaganda: \{ column: 2, row: 9 \}/, "military technology positions must define war propaganda at row nine column two");
assert.match(app, /trench_works: \{ column: 5, row: 9 \}/, "military technology positions must define trench works at row nine column five");
assert.match(app, /wargaming: \{ column: 7, row: 9 \}/, "military technology positions must define wargaming at row nine column seven");
assert.match(app, /mobile_armor: \{ column: 6, row: 12 \}/, "military technology positions must define mobile armor at row twelve column six");
assert.match(app, /navigation: \{ column: 20, row: 1 \}/, "military technology positions must define navigation at row one column twenty");
assert.match(app, /concrete_dockyards: \{ column: 24, row: 9 \}/, "military technology positions must define concrete dockyards at row nine column twenty-four");
assert.match(app, /battlefleet_tactics: \{ column: 20, row: 12 \}/, "military technology positions must define battlefleet tactics at row twelve column twenty");
assert.match(app, /gantry_cranes: \{ column: 22, row: 7 \}/, "military technology positions must define gantry cranes at row seven column twenty-two");
assert.match(app, /floating_harbor: \{ column: 23, row: 8 \}/, "military technology positions must define floating harbor at row eight column twenty-three");
assert.match(app, /society: \{[\s\S]*?urbanization: \{ column: 7, row: 1 \}/, "society technology positions must define urbanization at row one column seven");
assert.match(app, /analytical_philosophy: \{ column: 29, row: 11 \}/, "society technology positions must define analytical philosophy at row eleven column twenty-nine");
assert.match(app, /mass_propaganda: \{ column: 22, row: 11 \}/, "society technology positions must define mass propaganda at row eleven column twenty-two");
assert.match(app, /technology-relation-tags/, "technology detail relationships must use a spaced tag container");
assert.match(styles, /\.technology-relation-tags \{ display: flex; flex-wrap: wrap; gap: 10px; \}/, "technology detail tags must have a 10px gap");
assert.match(fs.readFileSync(path.join(root, "site", "index.html"), "utf8"), /styles\.css\?v=20260718-detail-title1/, "stylesheet version must refresh the split source files");
for (const technology of technologyChunk.technologies) {
  const iconFile = path.basename(technology.icon).replace(/\.dds$/i, ".webp");
  assert(fs.existsSync(path.join(root, "site", "assets", "technologies", iconFile)), `${technology.key} must have a published WebP icon`);
}

console.log(JSON.stringify({ technology_board_contract: "ok" }, null, 2));

function readGlobal(file) {
  const source = fs.readFileSync(file, "utf8");
  const match = source.match(/window\.VIC3_DATA_CHUNK\s*=\s*(.+);\s*$/s);
  assert(match, "technology chunk must define VIC3_DATA_CHUNK");
  return JSON.parse(match[1]);
}
