import assert from "node:assert/strict";
import fs from "node:fs";

const boards = fs.readFileSync("site/app/boards.js", "utf8");
const components = fs.readFileSync("site/app/components.js", "utf8");
const ui = fs.readFileSync("site/app/ui.js", "utf8");
const runtime = fs.readFileSync("site/app/runtime.js", "utf8");
const styles = fs.readFileSync("site/styles/technology.css", "utf8");
const technologyListCardSource = boards.match(/function technologyListCard\(technology\)\s*\{([\s\S]*?)\n\}/)?.[1] || "";

assert.match(boards, /function renderTechnologyHome\(\)/, "technology home renderer must exist");
assert.match(boards, /function renderTechnologyList\(category\)/, "technology list renderer must exist");
assert.match(boards, /function renderTechnologyBoard\(category(?:\s*=\s*state\.technologyCategory)?\)/, "technology tree renderer must accept a category");
assert.match(boards, /renderTechnologyDetail\(/, "technology views must share one detail renderer");
assert.match(boards, /data-technology-mode="\$\{mode\}"/, "technology home must expose mode-labelled entries");
assert.match(boards, /technologyRoute\(mode, category\)/, "technology home entries must use category routes");
assert.match(boards, /\["production", "military", "society"\]/, "technology home must expose all three categories");
assert.match(boards, /technologyRoute\("list", category\)/, "technology home must expose list routes");
assert.match(boards, /technologyRoute\("tree", category\)/, "technology home must expose tree routes");
assert.match(boards, /board\.technology\.openList/, "technology home must label the list view");
assert.match(boards, /board\.technology\.openTree/, "technology home must label the tree view");
assert.match(ui, /\["list", "tree"\]/, "technology list and tree routes must be parsed");
assert.match(ui, /parts\[0\] === "technology" && \["list", "tree"\]/, "technology list and tree route branch must exist");
assert.match(ui, /state\.technologyMode/, "technology mode must be stored in state");
assert.match(runtime, /technologyMode:/, "technology mode must be part of runtime state");
assert.match(styles, /technology-home/, "technology home must have dedicated styles");
assert.match(styles, /technology-list/, "technology list must have dedicated styles");
assert.match(styles, /body\[data-view="technology"\] \.map-panel/, "technology page must hide the shared map panel");
assert.match(styles, /body\[data-view="technology"\] \.filters/, "technology page must hide the shared filters panel");
assert.match(styles, /body\[data-view="technology"\] \.results\s*\{/, "technology page must use a full-width results surface");
assert.match(styles, /technology-home-card[\s\S]*min-height/, "technology home cards must occupy a substantial content area");
assert.match(boards, /function technologyEffectSection\(technology\)/, "technology detail must separate persistent effects");
assert.match(boards, /function technologyResearchEffectSection\(technology\)/, "technology detail must separate research-completion effects");
assert.match(boards, /data-technology-research-effect/, "technology detail must expose research-completion effects");
assert.match(boards, /technology\.research_results/, "technology detail must read structured research-completion data");
assert.match(boards, /production_methods/, "technology detail must expose production method content");
assert.match(boards, /references\.buildings/, "technology detail must expose building content");
assert.match(boards, /references\.production_methods/, "technology detail must expose production method content");
assert.match(boards, /references\.combat_units/, "technology detail must expose land combat unit content");
assert.match(boards, /references\.ship_types/, "technology detail must expose naval ship content");
assert.match(boards, /references\.mobilization_options/, "technology detail must expose mobilization option content");
assert.match(boards, /references\.diplomatic_actions/, "technology detail must expose diplomatic action content");
assert.match(boards, /references\.treaty_articles/, "technology detail must expose treaty article content");
assert.match(boards, /references\.parties/, "technology detail must expose party unlock content");
assert.match(boards, /technologyReferenceIcon\(item, "party"\)/, "technology party references must use party icons");
assert.match(boards, /technology-unit-icon/, "technology unit references must use unit icon assets");
assert.match(boards, /function technologyReferenceEntity\(item, kind\)/, "technology content references must resolve to localized records");
assert.match(boards, /economyEntityIconHtml\(/, "technology content references must reuse economy icons");
assert.match(boards, /buildingRecordByKey\.get\(item\.key\)/, "technology building references must use the complete building records");
assert.match(components, /entity\?\.icon_path/, "economy icon rendering must accept technology reference icon paths");
assert.match(boards, /standaloneSiteConfig/, "VC-only technology filters must be conditional");
assert.match(boards, /data-technology-list-results/, "technology list results must have a stable container");
assert.match(boards, /preserveSearchFocus/, "technology tree search must preserve the input focus");
assert.match(boards, /technologyContentChip\(item, "building"\)/, "technology list building references must be icon-only");
assert.match(boards, /technologyContentChip\(item, "production-method"\)/, "technology list production-method references must be icon-only");
assert.match(boards, /function dedupeTechnologyReferences\(items, kind\)/, "technology list production methods must be deduplicated");
assert.match(boards, /dedupeTechnologyReferences\(references\.production_methods/, "technology list must deduplicate production method references");
assert.match(boards, /technologyMatchesQuery\(technology, query\)/, "technology search must use the scoped technology matcher");
assert.match(boards, /technology-effect-text/, "technology text effects must use a separate text group");
assert.match(boards, /technology-effect-icons/, "technology icon effects must use a separate icon group");
assert.match(boards, /technology\.vc_change_kind/, "technology list must expose VC change state");
assert.match(boards, /item\.vc_change_kind\s*\?\s*" technology-vc-effect"/, "VC technology effects must expose per-effect change state");
assert.match(styles, /technology-vc-effect/, "VC changed technology effects must have a distinct color");
assert.doesNotMatch(styles, /technology-list-card\.technology-vc-adjusted/, "VC adjusted technologies must not recolor the entire card");
assert.doesNotMatch(styles, /technology-list-card\.technology-vc-added/, "VC added technologies must not recolor the entire card");
assert.match(boards, /technology-effect-text/, "technology text effects must be separated from icon effects");
assert.match(boards, /technology-effect-icons/, "technology icon effects must be separated from text effects");
assert.doesNotMatch(boards, /technology-no-projected-content/, "technology list must not show an empty projected content placeholder");
assert.doesNotMatch(technologyListCardSource, /technology\.unlocks/, "technology list must not render subsequent technologies as projected content");
assert.match(boards, /function technologyListOrder\(category\)/, "technology list must use the technology tree order");
assert.match(boards, /technologyListOrder\(category\)/, "technology list renderer must apply the technology tree order");
assert.doesNotMatch(boards, /sort\(\(left, right\) => Number\(left\.sort_order/, "technology list must not use source definition order");
assert.match(styles, /body\.detail-page\[data-view="technology"\] \.detail[\s\S]*position:\s*fixed/, "technology detail panel must be fixed");
assert.match(styles, /body\.detail-page\[data-view="technology"\] \.results[\s\S]*overflow-y:\s*auto/, "technology results must scroll independently");
assert.match(styles, /\.technology-content-chip\s*\{[^}]*background:\s*transparent/, "technology icon chips must not have a container background");
assert.match(styles, /\.technology-content-icon\s*\{[^}]*width:\s*32px[^}]*height:\s*32px/, "technology content icons must be enlarged");

console.log(JSON.stringify({ technology_navigation_contract: "ok" }, null, 2));
