import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";

const root = process.cwd();
const read = (file) => fs.readFileSync(path.join(root, file), "utf8");
const index = read("site/versions/1.13.9/data-index.js");
const html = read("site/index.html");
const runtime = read("site/app/runtime.js");
const data = read("site/app/data.js");
const ui = read("site/app/ui.js");
const boards = read("site/app/boards.js");
const characters = read("site/app/characters.js");
const pools = read("site/app/name-pools.js");
const styles = read("site/styles/characters.css");
const search = read("site/versions/1.13.9/search-index.js");

assert.match(html, /data-nav-view="character"/, "missing character navigation entry");
assert.match(html, /data-nav-view="name-pool"/, "missing name-pool navigation entry");
assert.match(index, /data-characters\.js/, "data index must register character chunk");
assert.match(index, /data-character-images\.js/, "data index must register historical character image chunk");
assert.match(index, /data-name-pools\.js/, "data index must register name-pool chunk");
assert.match(runtime, /let historicalCharacters = \[\];/, "runtime must store historical characters");
assert.match(runtime, /let historicalCharacterImages = \[\];/, "runtime must store historical character images");
assert.match(data, /byHistoricalCharacterImage = new Map\(/, "data loader must index historical character images by template key");
assert.match(runtime, /let namePools = \[\];/, "runtime must store name pools");
assert.match(data, /view === "character"/, "data loader must recognize character view");
assert.match(data, /view === "name-pool"/, "data loader must recognize name-pool view");
assert.match(ui, /renderCharacterBoard\(\)/, "ui must dispatch character board");
assert.match(ui, /renderNamePoolBoard\(\)/, "ui must dispatch name-pool board");
assert.match(characters, /function renderCharacterBoard\(/, "character board renderer missing");
assert.match(characters, /function renderHistoricalCharacterDetail\(/, "character detail renderer missing");
assert.match(characters, /byHistoricalCharacterImage\.get\(character\.key\)/, "character UI must read the historical image index");
assert.match(characters, /board\.character\.hasHistoricalImage/, "character rows must label confirmed historical images");
assert.match(characters, /character-historical-image/, "character details must render confirmed historical images");
assert.match(characters, /image\.thumbnail_url/, "character details must use the collected thumbnail");
assert.match(characters, /image\.file_page/, "character details must link to the Commons file page");
assert.match(pools, /function renderNamePoolBoard\(/, "name-pool board renderer missing");
assert.match(pools, /male_common_first_names/, "name-pool board must render fixed name pools");
assert.match(styles, /body\[data-view="character"\]/, "character board styles missing");
assert.match(styles, /body\[data-view="name-pool"\]/, "name-pool board styles missing");
assert.match(styles, /grid-template-columns: var\(--role-filter-width\) minmax\(0, 1fr\) var\(--role-detail-width\)/, "role board must use its own three-column layout");
assert.match(styles, /filter-section:not\(\.character-only\)/, "character board must isolate its filters");
assert.match(styles, /grid-template-columns: none !important/, "character rows must not inherit the country grid template");
assert.match(characters, /character_trait:\$\{normalized\}\.name/, "character traits must use the character localization namespace");
assert.match(characters, /const CHARACTER_PAGE_SIZE = 100/, "character board must cap each page at 100 rows");
assert.match(characters, /state\.characterPage/, "character board must keep the current page in state");
assert.match(characters, /filtered\.slice\(/, "character board must paginate after filtering and sorting");
assert.match(characters, /data-character-page=/, "character board must render pagination controls");
assert.match(search, /"kind":"character"/, "search index must include characters");
assert.match(search, /"kind":"namePool"/, "search index must include name pools");
assert.match(boards, /kind === "character"/, "global search must navigate to characters");
assert.match(boards, /kind === "namePool"/, "global search must navigate to name pools");

console.log("character board contract check passed");
